In [1]:
import tensorflow as tf
from tensorflow.python.keras import layers
from tensorflow.python.keras.optimizers import adam_v2
from tensorflow.python.keras import losses
from typing import List
import os
import numpy as np

In [2]:
class SimpleModel(tf.keras.Model):
    """
    Model class. Quite simple. Complete this docstring is a #TODO
    """

    def __init__(self, hidden_sizes: List, target_size: int) -> None:
        """
        Initialize a QNET with N hidden layers, where N is the length of the 
        hidden_sizes list. Each layer i has n nodes, being n the value of ith
        element of the hidden_sizes list. These layers are activated with a relu
        function.

        Finally a Dense layer of target_size nodes without activation is used as
        an output layer.
        """
        super().__init__()
        # self.input_layer = layers.InputLayer(input_shape=input_shape)
        self.hidden_layers = []
        for count, layer_size in enumerate(hidden_sizes):
            if count == 0:
                self.hidden_layers.append(layers.Dense(
                    layer_size,  activation='relu', name=f'hidden{count}'))
            else:
                self.hidden_layers.append(layers.Dense(
                    layer_size, activation='relu', name=f'hidden{count}'))

        self.output_layer = layers.Dense(
            target_size, activation=None, name='output')

        # TODO: Maybe adding Dropouts to improve the model

    def call(self, input):
        """
        Will be called when predict and train.
        """
        for layer in self.hidden_layers:
            x = layer(input)
            input = tf.identity(x)

        return self.output_layer(x)

    def save(self, file_name='model.pth'):
        """
        Save the entire model.
        """
        folder_path = './model'
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)

        file_name = os.path.join(folder_path, file_name)
        self.save(file_name=file_name)


In [3]:
ones = tf.ones((1,10))
ones

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [5]:
model = SimpleModel([10,10],3)
model.predict(ones)

1/1 [==============================] - 0s 212ms/step


array([[0.09015599, 0.99018365, 0.46618605]], dtype=float32)

In [7]:
logit = model(ones)
logit

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.09015599, 0.99018365, 0.46618605]], dtype=float32)>